default_language_version:
    python: python3

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        language_version: python3
        exclude: conda-recipe/meta.yaml
    -   id: debug-statements
        language_version: python3
    -   id: end-of-file-fixer
        language_version: python3
        exclude: .ipynb|.txt|.sld
    -   id: trailing-whitespace
        language_version: python3
        exclude: .txt|.sld

-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    -   id: black
        args: ["--target-version", "py36"]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]


-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ['--config=setup.cfg']

-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.1
    hooks:
    -   id: pydocstyle
        language_version: python3
        args: ['--convention=numpy', '--match="(?!test_).*\.py"']

-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes

ci:
    autoupdate_schedule: quarterly
    skip: []
    submodules: false
